// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package mymonies is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Account
	Tag
	Transaction
	TransactionFilter
	Pattern
	AddImportReq
	AddImportResp
	AddPatternReq
	AddPatternResp
	ListAccountsReq
	ListAccountsResp
	ListTagsReq
	ListTagsResp
	ListTransactionsReq
	ListTransactionsResp
	UpdateTagReq
	UpdateTagResp
*/
package mymonies

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Number string `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type Tag struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Tag) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Transaction struct {
	Id              string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TransactionDate string  `protobuf:"bytes,2,opt,name=transaction_date,json=transactionDate" json:"transaction_date,omitempty"`
	ValueDate       string  `protobuf:"bytes,3,opt,name=value_date,json=valueDate" json:"value_date,omitempty"`
	PaymentDate     string  `protobuf:"bytes,4,opt,name=payment_date,json=paymentDate" json:"payment_date,omitempty"`
	Amount          float64 `protobuf:"fixed64,5,opt,name=amount" json:"amount,omitempty"`
	PayeePayer      string  `protobuf:"bytes,6,opt,name=payee_payer,json=payeePayer" json:"payee_payer,omitempty"`
	Account         string  `protobuf:"bytes,7,opt,name=account" json:"account,omitempty"`
	Bic             string  `protobuf:"bytes,8,opt,name=bic" json:"bic,omitempty"`
	Transaction     string  `protobuf:"bytes,9,opt,name=transaction" json:"transaction,omitempty"`
	Reference       string  `protobuf:"bytes,10,opt,name=reference" json:"reference,omitempty"`
	PayerReference  string  `protobuf:"bytes,11,opt,name=payer_reference,json=payerReference" json:"payer_reference,omitempty"`
	Message         string  `protobuf:"bytes,12,opt,name=message" json:"message,omitempty"`
	CardNumber      string  `protobuf:"bytes,13,opt,name=card_number,json=cardNumber" json:"card_number,omitempty"`
	TagId           string  `protobuf:"bytes,14,opt,name=tag_id,json=tagId" json:"tag_id,omitempty"`
	ImportId        string  `protobuf:"bytes,15,opt,name=import_id,json=importId" json:"import_id,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetTransactionDate() string {
	if m != nil {
		return m.TransactionDate
	}
	return ""
}

func (m *Transaction) GetValueDate() string {
	if m != nil {
		return m.ValueDate
	}
	return ""
}

func (m *Transaction) GetPaymentDate() string {
	if m != nil {
		return m.PaymentDate
	}
	return ""
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetPayeePayer() string {
	if m != nil {
		return m.PayeePayer
	}
	return ""
}

func (m *Transaction) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Transaction) GetBic() string {
	if m != nil {
		return m.Bic
	}
	return ""
}

func (m *Transaction) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

func (m *Transaction) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Transaction) GetPayerReference() string {
	if m != nil {
		return m.PayerReference
	}
	return ""
}

func (m *Transaction) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Transaction) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *Transaction) GetTagId() string {
	if m != nil {
		return m.TagId
	}
	return ""
}

func (m *Transaction) GetImportId() string {
	if m != nil {
		return m.ImportId
	}
	return ""
}

type TransactionFilter struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Month   string `protobuf:"bytes,3,opt,name=month" json:"month,omitempty"`
	Query   string `protobuf:"bytes,4,opt,name=query" json:"query,omitempty"`
}

func (m *TransactionFilter) Reset()                    { *m = TransactionFilter{} }
func (m *TransactionFilter) String() string            { return proto.CompactTextString(m) }
func (*TransactionFilter) ProtoMessage()               {}
func (*TransactionFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransactionFilter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TransactionFilter) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *TransactionFilter) GetMonth() string {
	if m != nil {
		return m.Month
	}
	return ""
}

func (m *TransactionFilter) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Pattern struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Query   string `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	TagId   string `protobuf:"bytes,3,opt,name=tag_id,json=tagId" json:"tag_id,omitempty"`
}

func (m *Pattern) Reset()                    { *m = Pattern{} }
func (m *Pattern) String() string            { return proto.CompactTextString(m) }
func (*Pattern) ProtoMessage()               {}
func (*Pattern) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Pattern) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Pattern) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Pattern) GetTagId() string {
	if m != nil {
		return m.TagId
	}
	return ""
}

type AddImportReq struct {
	Account      string         `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	FileName     string         `protobuf:"bytes,2,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,3,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *AddImportReq) Reset()                    { *m = AddImportReq{} }
func (m *AddImportReq) String() string            { return proto.CompactTextString(m) }
func (*AddImportReq) ProtoMessage()               {}
func (*AddImportReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AddImportReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AddImportReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *AddImportReq) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type AddImportResp struct {
}

func (m *AddImportResp) Reset()                    { *m = AddImportResp{} }
func (m *AddImportResp) String() string            { return proto.CompactTextString(m) }
func (*AddImportResp) ProtoMessage()               {}
func (*AddImportResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type AddPatternReq struct {
	Pattern *Pattern `protobuf:"bytes,1,opt,name=pattern" json:"pattern,omitempty"`
}

func (m *AddPatternReq) Reset()                    { *m = AddPatternReq{} }
func (m *AddPatternReq) String() string            { return proto.CompactTextString(m) }
func (*AddPatternReq) ProtoMessage()               {}
func (*AddPatternReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AddPatternReq) GetPattern() *Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

type AddPatternResp struct {
}

func (m *AddPatternResp) Reset()                    { *m = AddPatternResp{} }
func (m *AddPatternResp) String() string            { return proto.CompactTextString(m) }
func (*AddPatternResp) ProtoMessage()               {}
func (*AddPatternResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ListAccountsReq struct {
}

func (m *ListAccountsReq) Reset()                    { *m = ListAccountsReq{} }
func (m *ListAccountsReq) String() string            { return proto.CompactTextString(m) }
func (*ListAccountsReq) ProtoMessage()               {}
func (*ListAccountsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ListAccountsResp struct {
	Accounts []*Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
}

func (m *ListAccountsResp) Reset()                    { *m = ListAccountsResp{} }
func (m *ListAccountsResp) String() string            { return proto.CompactTextString(m) }
func (*ListAccountsResp) ProtoMessage()               {}
func (*ListAccountsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ListAccountsResp) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type ListTagsReq struct {
}

func (m *ListTagsReq) Reset()                    { *m = ListTagsReq{} }
func (m *ListTagsReq) String() string            { return proto.CompactTextString(m) }
func (*ListTagsReq) ProtoMessage()               {}
func (*ListTagsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ListTagsResp struct {
	Tags []*Tag `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
}

func (m *ListTagsResp) Reset()                    { *m = ListTagsResp{} }
func (m *ListTagsResp) String() string            { return proto.CompactTextString(m) }
func (*ListTagsResp) ProtoMessage()               {}
func (*ListTagsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ListTagsResp) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ListTransactionsReq struct {
	Filter *TransactionFilter `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
}

func (m *ListTransactionsReq) Reset()                    { *m = ListTransactionsReq{} }
func (m *ListTransactionsReq) String() string            { return proto.CompactTextString(m) }
func (*ListTransactionsReq) ProtoMessage()               {}
func (*ListTransactionsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListTransactionsReq) GetFilter() *TransactionFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ListTransactionsResp struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *ListTransactionsResp) Reset()                    { *m = ListTransactionsResp{} }
func (m *ListTransactionsResp) String() string            { return proto.CompactTextString(m) }
func (*ListTransactionsResp) ProtoMessage()               {}
func (*ListTransactionsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ListTransactionsResp) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type UpdateTagReq struct {
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	TagId         string `protobuf:"bytes,2,opt,name=tag_id,json=tagId" json:"tag_id,omitempty"`
}

func (m *UpdateTagReq) Reset()                    { *m = UpdateTagReq{} }
func (m *UpdateTagReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateTagReq) ProtoMessage()               {}
func (*UpdateTagReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UpdateTagReq) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *UpdateTagReq) GetTagId() string {
	if m != nil {
		return m.TagId
	}
	return ""
}

type UpdateTagResp struct {
}

func (m *UpdateTagResp) Reset()                    { *m = UpdateTagResp{} }
func (m *UpdateTagResp) String() string            { return proto.CompactTextString(m) }
func (*UpdateTagResp) ProtoMessage()               {}
func (*UpdateTagResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func init() {
	proto.RegisterType((*Account)(nil), "com.github.joneskoo.mymonies.Account")
	proto.RegisterType((*Tag)(nil), "com.github.joneskoo.mymonies.Tag")
	proto.RegisterType((*Transaction)(nil), "com.github.joneskoo.mymonies.Transaction")
	proto.RegisterType((*TransactionFilter)(nil), "com.github.joneskoo.mymonies.TransactionFilter")
	proto.RegisterType((*Pattern)(nil), "com.github.joneskoo.mymonies.Pattern")
	proto.RegisterType((*AddImportReq)(nil), "com.github.joneskoo.mymonies.AddImportReq")
	proto.RegisterType((*AddImportResp)(nil), "com.github.joneskoo.mymonies.AddImportResp")
	proto.RegisterType((*AddPatternReq)(nil), "com.github.joneskoo.mymonies.AddPatternReq")
	proto.RegisterType((*AddPatternResp)(nil), "com.github.joneskoo.mymonies.AddPatternResp")
	proto.RegisterType((*ListAccountsReq)(nil), "com.github.joneskoo.mymonies.ListAccountsReq")
	proto.RegisterType((*ListAccountsResp)(nil), "com.github.joneskoo.mymonies.ListAccountsResp")
	proto.RegisterType((*ListTagsReq)(nil), "com.github.joneskoo.mymonies.ListTagsReq")
	proto.RegisterType((*ListTagsResp)(nil), "com.github.joneskoo.mymonies.ListTagsResp")
	proto.RegisterType((*ListTransactionsReq)(nil), "com.github.joneskoo.mymonies.ListTransactionsReq")
	proto.RegisterType((*ListTransactionsResp)(nil), "com.github.joneskoo.mymonies.ListTransactionsResp")
	proto.RegisterType((*UpdateTagReq)(nil), "com.github.joneskoo.mymonies.UpdateTagReq")
	proto.RegisterType((*UpdateTagResp)(nil), "com.github.joneskoo.mymonies.UpdateTagResp")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 765 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdb, 0x6a, 0xdb, 0x4a,
	0x14, 0x45, 0x76, 0x7c, 0xdb, 0xbe, 0x66, 0x4e, 0x4e, 0x10, 0x4e, 0x0e, 0xc7, 0x11, 0x84, 0xc6,
	0x69, 0xeb, 0x52, 0x97, 0x3e, 0x97, 0x94, 0x5e, 0x30, 0x24, 0xc1, 0x88, 0xe4, 0xa5, 0x0f, 0x35,
	0x63, 0x69, 0xa2, 0xa8, 0x8d, 0xa4, 0xb1, 0x66, 0x1c, 0xf0, 0x3f, 0xf4, 0xb1, 0xff, 0xd4, 0xdf,
	0x2a, 0x73, 0x91, 0x3d, 0xae, 0xc1, 0x72, 0xe8, 0x8b, 0xd1, 0xac, 0xbd, 0xd6, 0xd6, 0xbe, 0xac,
	0x11, 0x86, 0x26, 0x23, 0xe9, 0x63, 0xe8, 0x91, 0x01, 0x4d, 0x13, 0x9e, 0xa0, 0x63, 0x2f, 0x89,
	0x06, 0x41, 0xc8, 0xef, 0xe7, 0xd3, 0xc1, 0xb7, 0x24, 0x26, 0xec, 0x7b, 0x92, 0x0c, 0xa2, 0x45,
	0x94, 0xc4, 0x21, 0x61, 0xce, 0x09, 0x54, 0x2e, 0x3c, 0x2f, 0x99, 0xc7, 0x1c, 0x1d, 0x42, 0x39,
	0x9e, 0x47, 0x53, 0x92, 0xda, 0x56, 0xcf, 0x3a, 0xab, 0xb9, 0xfa, 0xe4, 0xf4, 0xa1, 0x78, 0x83,
	0x03, 0xd4, 0x82, 0x42, 0xe8, 0xeb, 0x50, 0x21, 0xf4, 0x11, 0x82, 0xbd, 0x18, 0x47, 0xc4, 0x2e,
	0x48, 0x44, 0x3e, 0x3b, 0xbf, 0x8a, 0x50, 0xbf, 0x49, 0x71, 0xcc, 0xb0, 0xc7, 0xc3, 0x24, 0xde,
	0xd0, 0xf4, 0xa1, 0xc3, 0x57, 0xe1, 0x89, 0x8f, 0x79, 0xa6, 0x6f, 0x1b, 0xf8, 0x07, 0xcc, 0x09,
	0xfa, 0x0f, 0xe0, 0x11, 0x3f, 0xcc, 0x89, 0x22, 0x15, 0x25, 0xa9, 0x26, 0x11, 0x19, 0x3e, 0x81,
	0x06, 0xc5, 0x8b, 0x88, 0xc4, 0x5c, 0x11, 0xf6, 0x24, 0xa1, 0xae, 0x31, 0x49, 0x39, 0x84, 0x32,
	0x8e, 0x44, 0x67, 0x76, 0xa9, 0x67, 0x9d, 0x59, 0xae, 0x3e, 0xa1, 0xff, 0x41, 0xd0, 0x08, 0x99,
	0x88, 0xdf, 0xd4, 0x2e, 0x4b, 0x25, 0x48, 0x68, 0x2c, 0x10, 0x64, 0x43, 0x05, 0xab, 0x99, 0xd8,
	0x15, 0x19, 0xcc, 0x8e, 0xa8, 0x03, 0xc5, 0x69, 0xe8, 0xd9, 0x55, 0x89, 0x8a, 0x47, 0xd4, 0x83,
	0xba, 0x51, 0xb9, 0x5d, 0x53, 0x65, 0x18, 0x10, 0x3a, 0x86, 0x5a, 0x4a, 0xee, 0x48, 0x4a, 0x62,
	0x8f, 0xd8, 0xa0, 0xfa, 0x58, 0x02, 0xe8, 0x19, 0xb4, 0x65, 0x19, 0x93, 0x15, 0xa7, 0x2e, 0x39,
	0x2d, 0x09, 0xbb, 0x4b, 0xa2, 0x0d, 0x95, 0x88, 0x30, 0x86, 0x03, 0x62, 0x37, 0x54, 0x51, 0xfa,
	0x28, 0xfa, 0xf1, 0x70, 0xea, 0x4f, 0xf4, 0xf2, 0x9a, 0xaa, 0x1f, 0x01, 0x5d, 0x4b, 0x04, 0xfd,
	0x0b, 0x65, 0x8e, 0x83, 0x49, 0xe8, 0xdb, 0x2d, 0x19, 0x2b, 0x71, 0x1c, 0x8c, 0x7c, 0x74, 0x04,
	0xb5, 0x30, 0xa2, 0x49, 0xca, 0x45, 0xa4, 0x2d, 0x23, 0x55, 0x05, 0x8c, 0x7c, 0x27, 0x84, 0x7d,
	0x63, 0x91, 0x9f, 0xc2, 0x07, 0x4e, 0xd2, 0x8d, 0x75, 0x1a, 0x83, 0x2a, 0xac, 0x0f, 0xea, 0x00,
	0x4a, 0x51, 0x12, 0xf3, 0x7b, 0xbd, 0x38, 0x75, 0x10, 0xe8, 0x6c, 0x4e, 0xd2, 0x85, 0xde, 0x96,
	0x3a, 0x38, 0x63, 0xa8, 0x8c, 0x31, 0xe7, 0x24, 0x8d, 0xcd, 0x84, 0xd6, 0x46, 0x42, 0x25, 0x2d,
	0x18, 0x52, 0xa3, 0xb3, 0xa2, 0xd1, 0x99, 0xf3, 0xd3, 0x82, 0xc6, 0x85, 0xef, 0x8f, 0x64, 0x33,
	0x2e, 0x99, 0x6d, 0xc9, 0x7b, 0x04, 0xb5, 0xbb, 0xf0, 0x81, 0x4c, 0x0c, 0x2b, 0x57, 0x05, 0x70,
	0x8d, 0x23, 0x82, 0xae, 0xa0, 0x61, 0x6c, 0x92, 0xd9, 0xc5, 0x5e, 0xf1, 0xac, 0x3e, 0xec, 0x0f,
	0xb6, 0xdd, 0xa8, 0x81, 0x31, 0x36, 0x77, 0x4d, 0xee, 0xb4, 0xa1, 0x69, 0x54, 0xc5, 0xa8, 0x33,
	0x96, 0x80, 0x6e, 0x5e, 0xd4, 0xf9, 0x0e, 0x2a, 0x54, 0x9d, 0x64, 0x9d, 0xf5, 0xe1, 0xe9, 0xf6,
	0x77, 0x65, 0xd2, 0x4c, 0xe5, 0x74, 0xa0, 0x65, 0x66, 0x64, 0xd4, 0xd9, 0x87, 0xf6, 0x65, 0xc8,
	0xb8, 0xbe, 0xe4, 0xcc, 0x25, 0x33, 0xe7, 0x16, 0x3a, 0xeb, 0x10, 0xa3, 0xe8, 0x02, 0xaa, 0x7a,
	0x24, 0xcc, 0xb6, 0x64, 0x9b, 0x39, 0xaf, 0xd6, 0x6a, 0x77, 0x29, 0x73, 0x9a, 0x50, 0x17, 0x69,
	0x6f, 0x70, 0x20, 0xdf, 0xf2, 0x11, 0x1a, 0xab, 0x23, 0xa3, 0xe8, 0x2d, 0xec, 0x71, 0x1c, 0x64,
	0xd9, 0x4f, 0x72, 0x86, 0x88, 0x03, 0x57, 0xd2, 0x9d, 0xaf, 0xf0, 0x8f, 0x4c, 0x63, 0x0c, 0x52,
	0x4c, 0xea, 0x33, 0x94, 0xef, 0xa4, 0x29, 0xf5, 0xa0, 0x5e, 0xed, 0xbc, 0x14, 0xe5, 0x65, 0x57,
	0xcb, 0x1d, 0x02, 0x07, 0x9b, 0xf9, 0x19, 0xdd, 0xd8, 0xbd, 0xf5, 0x77, 0xbb, 0xbf, 0x84, 0xc6,
	0x2d, 0x15, 0x5f, 0x2a, 0xd1, 0x19, 0x99, 0xa1, 0x53, 0x68, 0x99, 0x5f, 0xc2, 0xe5, 0xb5, 0x6a,
	0x1a, 0xe8, 0xc8, 0x37, 0x0c, 0x5e, 0x30, 0x0d, 0xde, 0x86, 0xa6, 0x91, 0x8d, 0xd1, 0xe1, 0x8f,
	0x12, 0x54, 0xaf, 0x74, 0x15, 0xc8, 0x87, 0xda, 0xd2, 0x67, 0xe8, 0x3c, 0x67, 0x8d, 0xc6, 0x35,
	0xe9, 0x3e, 0xdf, 0x99, 0xcb, 0x28, 0x0a, 0x00, 0x56, 0x56, 0x43, 0xf9, 0xd2, 0x95, 0xcd, 0xbb,
	0x2f, 0x76, 0x27, 0x33, 0x8a, 0x22, 0x65, 0xa4, 0xcc, 0xae, 0xe8, 0xe5, 0x76, 0xf5, 0x1f, 0x6e,
	0xef, 0x0e, 0x9e, 0x42, 0x67, 0x14, 0x61, 0xa8, 0x66, 0xbe, 0x45, 0xfd, 0x7c, 0xad, 0xb6, 0x7b,
	0xf7, 0x7c, 0x57, 0x2a, 0xa3, 0x68, 0xa1, 0x2e, 0xa0, 0xe9, 0x39, 0xf4, 0x7a, 0x07, 0xfd, 0xfa,
	0x1d, 0xe8, 0x0e, 0x9f, 0x2a, 0x61, 0x54, 0x78, 0x63, 0xe9, 0x9c, 0x3c, 0x6f, 0x98, 0x86, 0xcd,
	0xf3, 0xc6, 0x9a, 0x1d, 0xdf, 0xc3, 0x97, 0x6a, 0x16, 0x99, 0x96, 0xe5, 0xdf, 0x90, 0x37, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x09, 0x44, 0xa6, 0x90, 0x97, 0x08, 0x00, 0x00,
}
