// Code generated by protoc-gen-twirp_browserjs v0.0.1, DO NOT EDIT.
// source: service.proto

// _request takes the HTTP method, URL path (this will usually contain the domain name)
// json body that will be sent to the server, a callback on successful requests and a
// callback for requests that error out.
var _request = function(method, path, body, onSuccess, onError) {
  var xhr = new XMLHttpRequest();
  xhr.open(method, path, true);
  xhr.setRequestHeader("Accept","application/json");
  xhr.setRequestHeader("Content-Type","application/json");

  xhr.onreadystatechange = function (e) {
    if (xhr.readyState == 4) {
      if (xhr.status == 204 || xhr.status == 205) {
        onSuccess();
      } else if (xhr.status == 200) {
        var value = JSON.parse(xhr.responseText);
        onSuccess(value);
      } else {
        var value = JSON.parse(xhr.responseText);
        onError(value);
      }
    }
  };

  if (body != null) {
    xhr.send(JSON.stringify(body));
  } else {
    xhr.send(null);
  }
};

// methods for MymoniesClient

var Mymonies_add_pattern = function(server_address, add_pattern_req, onSuccess, onError) {
  var full_method = server_address + "/twirp/" + "com.github.joneskoo.mymonies.Mymonies" + "/" + "AddPattern";
  _request("POST", full_method, add_pattern_req, onSuccess, onError);
};
var Mymonies_list_accounts = function(server_address, list_accounts_req, onSuccess, onError) {
  var full_method = server_address + "/twirp/" + "com.github.joneskoo.mymonies.Mymonies" + "/" + "ListAccounts";
  _request("POST", full_method, list_accounts_req, onSuccess, onError);
};
var Mymonies_list_tags = function(server_address, list_tags_req, onSuccess, onError) {
  var full_method = server_address + "/twirp/" + "com.github.joneskoo.mymonies.Mymonies" + "/" + "ListTags";
  _request("POST", full_method, list_tags_req, onSuccess, onError);
};
var Mymonies_list_transactions = function(server_address, list_transactions_req, onSuccess, onError) {
  var full_method = server_address + "/twirp/" + "com.github.joneskoo.mymonies.Mymonies" + "/" + "ListTransactions";
  _request("POST", full_method, list_transactions_req, onSuccess, onError);
};
var Mymonies_update_tag = function(server_address, update_tag_req, onSuccess, onError) {
  var full_method = server_address + "/twirp/" + "com.github.joneskoo.mymonies.Mymonies" + "/" + "UpdateTag";
  _request("POST", full_method, update_tag_req, onSuccess, onError);
};
